### ISSUE TITLE
Optimize the code 

### ISSUE THREAD

**Issue by Haripandey21** [malik672/Proposal_dao#1]
# In your Smart Contract, you can optimize your contract by : 
- Declare maxSupply as immutable.
-  Instead of doing this :- div(10000000000) , change it to div(10*9)
-  Follow the proper Naming convention in your Function's parameters,check here : https://docs.soliditylang.org/en/v0.4.25/style-guide.html#function-argument-names

**Comment by malik672** [comment]
thank you

**Comment by malik672** [comment]
i wrote this when i just started
